version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    reviewers:
      - "eigenein"
