[package]
name = "blitz-dashboard"
version = "0.1.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
description = "World of Tanks Blitz player's web dashboard"
license-file = "LICENSE"
documentation = "https://github.com/eigenein/blitz-dashboard"
repository = "https://github.com/eigenein/blitz-dashboard"
homepage = "https://github.com/eigenein/blitz-dashboard"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.6.0", features = ["std", "attributes"] }
chrono = { version = "0.4.19", features = ["serde"] }
chrono-humanize = "0.2.1"
clap = "3.0.0-beta.2"
crc16 = "0.4.0"
itertools = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.14"
lru_time_cache = "0.11.10"
maud = "0.22.1"
mongodb = { version = "2.0.0-beta", default-features = false, features = ["async-std-runtime", "bson-chrono-0_4"] }
sentry = { version = "0.22.0", default-features = false, features = ["backtrace", "contexts", "panic", "surf", "rustls", "anyhow", "log"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
simplelog = "0.10.0"
surf = { version = "2.2.0", default-features = false, features = ["h1-client-rustls", "middleware-logger", "encoding"] }
tide = { version = "0.16.0", default-features = false, features = ["h1-server", "logger"] }
