[package]
name = "blitz-dashboard"
version = "0.87.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
resolver = "2"
description = "World of Tanks Blitz player's web dashboard"
license-file = "LICENSE"
documentation = "https://github.com/eigenein/blitz-dashboard"
repository = "https://github.com/eigenein/blitz-dashboard"
homepage = "https://github.com/eigenein/blitz-dashboard"
readme = "README.md"

[profile.release]
lto = "fat"
codegen-units = 1

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
anyhow = "1.0.40"
bytes = "1.0.1"
chrono-humanize = "0.2.1"
fastrand = "1.5.0"
humantime = "2.1.0"
itertools = "0.10.0"
jemallocator = "0.3.2"
log = "0.4.14"
lru = "0.7.0"
maud = "0.22.2"
miniz_oxide = "0.4.4"
phf = { version = "0.10.0", features = ["macros"] }
rand = "0.8.4"
rand_distr = "0.4.2"
rmp-serde = "0.15.5"
rocket = "0.5.0-rc.1"
serde_json = "1.0.64"
serde_qs = "0.8.4"
smallvec = { version = "1.7.0", features = ["serde", "union", "const_generics", "const_new"] }
structopt = { version = "0.3.22", default_features = false, features = ["color", "suggestions"] }

[dependencies.tokio]
version = "1.9.0"
features = ["rt-multi-thread"]

[dependencies.futures]
version = "0.3.15"
default-features = false

[dependencies.reqwest]
version = "0.11.4"
default-features = false
features = ["rustls-tls", "gzip", "brotli", "deflate", "json"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.sentry]
version = "0.23.0"
default-features = false
features = ["reqwest", "rustls", "backtrace", "contexts", "panic", "anyhow", "log"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.sqlx]
version = "0.5.5"
default-features = false
features = ["runtime-tokio-rustls", "postgres", "chrono"]

[dependencies.redis]
version = "0.21.0"
default-features = false
features = ["aio", "tokio-comp", "streams"]

[dev-dependencies]
serde_json = "1.0.59"
