[package]
name = "blitz-dashboard"
version = "0.2.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
description = "World of Tanks Blitz player's web dashboard"
license-file = "LICENSE"
documentation = "https://github.com/eigenein/blitz-dashboard"
repository = "https://github.com/eigenein/blitz-dashboard"
homepage = "https://github.com/eigenein/blitz-dashboard"
readme = "README.md"

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.6.0", features = ["attributes"] }
chrono = { version = "0.4.19", features = ["serde"] }
chrono-humanize = "0.2.1"
clap = "3.0.0-beta.2"
http-types = "2.11.1"
humantime-serde = "1.0.1"
itertools = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.14"
lru_time_cache = "0.11.11"
maud = "0.22.2"
openssl = { version = "0.10", features = ["vendored"] }
rusqlite = "0.25.3"
sentry = { version = "0.22.0", features = ["anyhow", "log"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
serde_qs = "0.8.4"
simplelog = "0.10.0"
surf = { version = "2.2.0" }
tide = { version = "0.16.0" }
