[package]
name = "blitz-dashboard"
version = "0.1.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
description = "World of Tanks Blitz player's web dashboard"
license-file = "LICENSE"
documentation = "https://github.com/eigenein/blitz-dashboard"
repository = "https://github.com/eigenein/blitz-dashboard"
homepage = "https://github.com/eigenein/blitz-dashboard"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
async-std = { version = "1.6.0", features = ["std", "attributes"] }
serde = { version = "1.0", features = ["derive"] }
maud = "0.22.1"
clap = "3.0.0-beta.2"
simplelog = "0.10.0"
log = "0.4.14"
anyhow = "1.0.40"
tide-compress = "0.9.0"
surf = { version = "2.2.0", features = ["h1-client-rustls", "middleware-logger", "encoding"] }
serde_json = "1.0.59"
