[package]
name = "blitz-dashboard"
version = "0.31.6"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
resolver = "2"
description = "World of Tanks Blitz player's web dashboard"
license-file = "LICENSE"
documentation = "https://github.com/eigenein/blitz-dashboard"
repository = "https://github.com/eigenein/blitz-dashboard"
homepage = "https://github.com/eigenein/blitz-dashboard"
readme = "README.md"

[profile.release]
lto = "fat"
codegen-units = 1

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
anyhow = "1.0.40"
chrono-humanize = "0.2.1"
clap = "3.0.0-beta.2"
fastrand = "1.5.0"
humantime = "2.1.0"
itertools = "0.10.0"
log = "0.4.14"
maud = "0.22.2"
phf = { version = "0.9.0", features = ["macros"] }
rocket = "0.5.0-rc.1"
serde_json = "1.0.64"
serde_qs = "0.8.4"
simplelog = "0.10.0"
smallvec = "1.6.1"
tokio = "1.8.1"

[dependencies.futures]
version = "0.3.15"
default-features = false

[dependencies.reqwest]
version = "0.11.4"
default-features = false
features = ["rustls-tls", "gzip", "brotli", "deflate", "json"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.moka]
version = "0.5.0"
features = ["future"]

[dependencies.sentry]
version = "0.23.0"
default-features = false
features = ["reqwest", "rustls", "backtrace", "contexts", "panic", "anyhow", "log"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.sqlx]
version = "0.5.5"
default-features = false
features = ["runtime-tokio-rustls", "postgres", "chrono"]

[dev-dependencies]
serde_json = "1.0.59"
