[package]
name = "blitz-dashboard"
version = "0.150.12"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2021"
description = "World of Tanks Blitz player's web dashboard"
license-file = "LICENSE"
repository = "https://github.com/eigenein/blitz-dashboard"
homepage = "https://yastati.st"
readme = "README.md"

[profile.release]
lto = "fat"
codegen-units = 1
debug = 1

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
ahash = "0.7.6"
anyhow = "1.0.56"
chrono-humanize = "0.2.1"
fastrand = "1.7.0"
humantime = "2.1.0"
itertools = "0.10.3"
jemallocator = "0.3.2"
log = "0.4.16"
maud = "0.23.0"
miniz_oxide = "0.5.0"
phf = { version = "0.10.1", features = ["macros"] }
rand = "0.8.4"
rand_distr = "0.4.2"
rmp-serde = "1.0.0"
rocket = "0.5.0-rc.1"
serde_json = "1.0.78"
serde_qs = "0.9.1"
structopt = { version = "0.3.25", default_features = false, features = ["color", "suggestions"] }
tracing = { version = "0.1.33", features = ["std", "log-always"] }
tracing-futures = { version = "0.2.5", features = ["tokio"] }
tracing-subscriber = { version = "0.3.11", default_features = false, features = ["std", "registry"] }

[dependencies.tokio]
version = "1.15.0"
features = ["rt-multi-thread", "time"]

[dependencies.futures]
version = "0.3.19"
default-features = false

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["rustls-tls", "gzip", "brotli", "deflate", "json"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.sentry]
version = "0.25.0"
default-features = false
features = ["reqwest", "rustls", "backtrace", "contexts", "panic", "anyhow", "tracing"]

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dependencies.sqlx]
version = "0.5.11"
default-features = false
features = ["runtime-tokio-rustls", "postgres", "chrono"]

[dependencies.redis]
version = "0.21.4"
default-features = false
features = ["aio", "tokio-comp", "streams"]

[dev-dependencies]
serde_json = "1.0.78"

[build-dependencies]
rustversion = "1.0.6"
