edition = "2021"
fn_call_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
imports_granularity = "Module"
