name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: build-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up the toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - name: Install Cross
        run: cargo install cross
        env:
          CARGO_TARGET_DIR: ./target

      - name: Build blitz-dashboard.arm-unknown-linux-gnueabihf (Raspberry Pi 0/1)
        run: cross build --target arm-unknown-linux-gnueabihf --release

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: blitz-dashboard.arm-unknown-linux-gnueabihf
          path: target/arm-unknown-linux-gnueabihf/release/blitz-dashboard
