name: Publish

on:
  release:
    types: ["published"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set release version
        run: |
          echo 'version = "${{ github.ref_name }}"'
          sed -i -e 's/version = "0.0.0"/version = "${{ github.ref_name }}"/g' Cargo.toml
          sed -i -e 's/version = "0.0.0"/version = "${{ github.ref_name }}"/g' Cargo.lock

      - name: Rustup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Install Cross
        run: |
          wget --quiet https://github.com/rust-embedded/cross/releases/download/v0.2.1/cross-v0.2.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xvzf cross-v0.2.1-x86_64-unknown-linux-gnu.tar.gz

      - name: Build for ARMv7 (Raspberry Pi 2/3/4)
        run: ./cross build --target armv7-unknown-linux-gnueabihf --release

      - name: Build Changelog
        id: changelog
        uses: Bullrich/generate-release-changelog@master
        env:
          REPO: ${{ github.repository }}

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: eigenein
          SENTRY_PROJECT: yastatist
        with:
          version: ${{ github.ref_name }}

      - name: Upload blitz-dashboard.armv7-unknown-linux-gnueabihf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/armv7-unknown-linux-gnueabihf/release/blitz-dashboard
          asset_name: blitz-dashboard.armv7-unknown-linux-gnueabihf
          asset_content_type: application/octet-stream

      - name: Update release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: false
