name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Rustup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Install Cross
        run: |
          wget https://github.com/rust-embedded/cross/releases/download/v0.2.1/cross-v0.2.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xvzf cross-v0.2.1-x86_64-unknown-linux-gnu.tar.gz

      - name: Build for ARMv7 (Raspberry Pi 2/3/4)
        run: ./cross build --target armv7-unknown-linux-gnueabihf --release

      - name: Build Changelog
        id: changelog
        uses: Bullrich/generate-release-changelog@master
        env:
          REPO: ${{ github.repository }}

      - name: Create a GitHub Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.changelog.outputs.changelog}}
          draft: false
          prerelease: false

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: eigenein
          SENTRY_PROJECT: yastatist
        with:
          version: ${{ github.ref }}

      - name: Upload blitz-dashboard.armv7-unknown-linux-gnueabihf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/armv7-unknown-linux-gnueabihf/release/blitz-dashboard
          asset_name: blitz-dashboard.armv7-unknown-linux-gnueabihf
          asset_content_type: application/octet-stream
